server:
  port: ${PORT:8081}

spring:
  threads:
    virtual:
      enabled: true
  mongodb:
    database: crud-starter

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 8.0.4

logging:
  level:
    org.springframework.context.support.PostProcessorRegistrationDelegate: ERROR
    de.flapdoodle.embed.mongo.spring.autoconfigure.EmbeddedMongo: WARN
