name: BACKEND - Node.js on Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: echo print content
      - run: ls

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install application dependencies
        working-directory: backend
        run: npm install


      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'crud-starter'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E2CCEEE9F6B3409D91BE2C1A6F88F3A9 }}
          package: backend
        env: # Add environment variables here
          MONGO_URI: ${{secrets.MONGO_URI}}